### ISSUE TITLE
Doesn't work when imported via HTTP or HTTPS URL

### ISSUE THREAD

**Issue by Haprog** [FurryWolfX/deno_exif#1]
Currently deno_exif doesn't seem to work when trying to import it from an HTTP(S) URL like so:

```ts
import { create } from 'https://deno.land/x/deno_exif@0.0.2/mod.ts';
```

If trying to use it with the above import I always get the following error:

![image](https://user-images.githubusercontent.com/75155/178122917-3962ccd5-83e9-477e-8c4a-d2d2ac4443e2.png)

<details>
<summary>Expand this to see the error as plain text</summary>

```
error: Uncaught (in promise) InvalidData: invalid url scheme
    throw new Deno.errors.InvalidData("invalid url scheme");
          ^
    at fileURLToPath (https://deno.land/std@0.88.0/node/url.ts:53:11)
    at createRequire (https://deno.land/std@0.88.0/node/module.ts:533:18)
    at https://deno.land/x/deno_exif@0.0.2/mod.ts:4:17
```

</details>

However if I clone the repository for example under a `lib/` dir in my project I can import it like this and it works without errors:

```ts
import { create } from './lib/deno_exif/mod.ts';
```

Using a `file://` URL also seems to work fine:

```ts
import { create } from 'file:///home/haprog/repos/cli-scripts/lib/deno_exif/mod.ts';
```

I also tested running a local HTTP server and importing from there with:

```ts
import { create } from 'http://127.0.0.1:8081/mod.ts';
```

But that also resulted in the same error above.

So for some reason this only seems to work when importing from local file system path but not when importing via HTTP or HTTPS.

Tested with deno 1.23.3.

**Comment by FurryWolfX** [comment]
Fixed in v0.0.3

**Comment by Haprog** [comment]
Thanks for quick response but unfortunately it still doesn't seem to work with 0.0.3 though now the error is different.

If I use 0.0.3 with:

```ts
import { create } from 'https://deno.land/x/deno_exif@0.0.3/mod.ts';
```

I get:

```
error: Uncaught (in promise) Error: Cannot find module './lib/parser.js'
Require stack:
- /home/haprog/repos/cli-scripts/testExifSimple.ts
      const err = new Error(message) as Error & {
                  ^
    at Function._resolveFilename (https://deno.land/std@0.88.0/node/module.ts:270:19)
    at Function._load (https://deno.land/std@0.88.0/node/module.ts:377:29)
    at Module.require (https://deno.land/std@0.88.0/node/module.ts:130:21)
    at require (https://deno.land/std@0.88.0/node/module.ts:1141:16)
    at https://deno.land/x/deno_exif@0.0.3/mod.ts:5:16
```

I think it is now trying to resolve the required files relative to my project dir instead of relative to the import URL. If I run my script within my local clone of deno_exif then it works even when importing via the above URL because I assume it just loads the rest of the files from local paths.

**Comment by Haprog** [comment]
Did 0.0.2 work imported via HTTPS URL in some previous version of deno or have you just been using it locally?

I'm just wondering would it make sense to try to test with different versions of deno to see if it broke in some specific version and figure out what changed. It could even be a bug in deno somehow related to importing CommonJS modules when using `createRequire` but I at least couldn't find any open issues in deno's repo which would seem related.

I just recently started using deno so I'm not quite sure how this kind of importing is supposed to work.

**Comment by Haprog** [comment]
Actually seems like this might be related https://github.com/denoland/deno_std/issues/955#issuecomment-856911465

I'm not sure if I understand this correctly, but maybe it means that `createRequire` can only be used to import locally and doesn't work for importing via HTTP/HTTPS? That would make it not very useful for libraries that you'd want to be importable directly via HTTP/HTTPS.

Btw I quickly converted all of the `lib/*` files from CJS to ESM format and with that change getting rid of the `createRequire` everything seems to work ok even when importing via HTTP.

I could do a PR for the ESM conversion if you like?

Basically all I had to do was:
1. Replace all `module.exports =` with `export default`
2. Update imports format from `var exif = require('./exif');` to `import exif from './exif.js';`
3. There was one conditional require `require('./exif-tags')` in `parser.js` which I just moved to the top of the file as a regular import so that it's always loaded (probably doesn't matter much in this simple case). It could have been changed to dynamic `import()` but that would probably have had to be awaited and then the containing function to be converted to async which would have required more changes so I didn't want to go that route.
4. Remove import of `createRequire` as it was unnecessary after these changes

Ps. I noticed I had to run `deno cache --reload=http://127.0.0.1:8081/ myTest.ts` after any changes I made when testing on a local HTTP server. Otherwise deno would use previously cached code for the dependencies when running my test script.
